//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloney {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloney.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use --{0}:&lt;path&gt; to specify a {1} folder.
        /// </summary>
        internal static string FolderArgumentErrorMessage {
            get {
                return ResourceManager.GetString("FolderArgumentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} folder does not contain a solution file.
        /// </summary>
        internal static string InvalidSolutionFolderExpression {
            get {
                return ResourceManager.GetString("InvalidSolutionFolderExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} folder does not exist.
        /// </summary>
        internal static string InvalidTargetFolderExpression {
            get {
                return ResourceManager.GetString("InvalidTargetFolderExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string MainErrorExpression {
            get {
                return ResourceManager.GetString("MainErrorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        internal static string SourceFolderArgumentName {
            get {
                return ResourceManager.GetString("SourceFolderArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        internal static string SourceFolderDisplayName {
            get {
                return ResourceManager.GetString("SourceFolderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the Cloney wizard....
        /// </summary>
        internal static string StartingWizardMessage {
            get {
                return ResourceManager.GetString("StartingWizardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        internal static string TargetFolderArgumentName {
            get {
                return ResourceManager.GetString("TargetFolderArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        internal static string TargetFolderDisplayName {
            get {
                return ResourceManager.GetString("TargetFolderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloney.Wizard.exe.
        /// </summary>
        internal static string WizardExecutable {
            get {
                return ResourceManager.GetString("WizardExecutable", resourceCulture);
            }
        }
    }
}
